apiVersion: v1
kind: Service
metadata:
  name: photo-album
  labels:
    app: album
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: album
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-album
  labels:
    app: album
spec:
  replicas: 1
  selector:
    matchLabels:
      app: album
  template:
    metadata:
      labels:
        app: album
    spec:
      containers:
      - name: photo-album
        image: chrisjen83/photo_album-arch:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
