apiVersion: apps/v1
kind: Deployment
metadata:
  name: centoslight01-dep
  labels:
    app: centoslight01-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: centoslight01-pod
      app: centoslight01-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: centoslight01-pod
      labels:
        name: centoslight01-pod
        app: centoslight01-app
    spec:
      containers:
        - name: centoslight01
          image: koutsane/koutsane:centoslight
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: "/mnt/isilon"
              name: centoslight01-vol01
      volumes:
        - name: centoslight01-vol01
          persistentVolumeClaim:
            claimName: isilon-csi-pvc
