apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isilon-csi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: isilon
  resources:
    requests:
      storage: 20Gi
