apiVersion: v1
kind: Service
metadata:
  name: ecs-meta-search-service
  labels:
    app: ecs-meta-search
spec:
  type: LoadBalancer
  ports:
    - port: 5000
  selector:
    app: ecs-meta-search
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecs-meta-search
spec:
  selector:
    matchLabels:
      app: ecs-meta-search
  replicas: 1
  template:
    metadata:
      labels:
        app: ecs-meta-search
    spec:
      containers:
      - name: ecs-meta-search
        image: chrisjen83/ecs-meta-search:v1
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: ecs-meta-search-configmap
